---
- hosts: k8s_controller_group, k8s_worker_group
  become: true
  tasks:
    - name: Stop kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Stop containerd service
      ansible.builtin.systemd:
        name: containerd
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Remove kubernetes packages (kubectl, kubeadm, kubelet)
      ansible.builtin.yum:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: absent

    - name: Remove containerd package
      ansible.builtin.yum:
        name: containerd
        state: absent

    # Reboot the system to ensure processes are cleared
    - name: Reboot the system
      ansible.builtin.reboot:
        msg: "Rebooting to clear any lingering Kubernetes-related processes"
        reboot_timeout: 600

    - name: Clean up any remaining Kubernetes dependencies
      ansible.builtin.command:
        cmd: yum autoremove -y
      ignore_errors: true

    - name: Remove Kubernetes configuration directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes
        - ~/.kube
        - /etc/etcd/
        - /var/lib/kubelet
        - /var/lib/etcd
        - /var/lib/cni
        - /opt/cni
        - /etc/cni
        - /var/run/kubernetes

    - name: Remove containerd configuration and data directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/containerd
        - /var/lib/containerd

    - name: Reload systemd daemon to remove any lingering services
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Verify removal of Kubernetes and containerd-related files
      ansible.builtin.shell: |
        find / -name '*kubelet*' -or -name '*kubectl*' -or -name '*kubeadm*' -or -name '*containerd*'
      register: remaining_files
      ignore_errors: true

    - name: Print remaining Kubernetes or containerd files (if any)
      ansible.builtin.debug:
        var: remaining_files.stdout_lines