---
- hosts: all
  become: true
  vars:
    domain_name: "aws.fivetuple.com"  # Replace with your domain
    email: "anonymous@aws.fivetuple.com"  # Email for LetsEncrypt notifications
    certs_dir: "/etc/pki/tls/"
    hosted_zone_id: "Z0158254IAVI6K6BNSO2"  # Replace with your Route 53 hosted zone ID

  tasks:
    - name: Install Certbot and Route 53 plugin using yum
      ansible.builtin.yum:
        name:
          - certbot
          - python3-certbot-dns-route53
        state: present
      tags: install

    - name: Create directory for SSL certificates
      ansible.builtin.file:
        path: "{{ certs_dir }}"
        state: directory
        mode: '0755'

    - name: Obtain Let's Encrypt certificate using DNS challenge (Route 53)
      ansible.builtin.command:
        cmd: >
          certbot certonly --dns-route53
          -d {{ domain_name }}
          --non-interactive
          --agree-tos
          --email {{ email }}
          --dns-route53-propagation-seconds 30
        tags: obtain_cert

    - name: Copy fullchain certificate to Nginx SSL directory
      ansible.builtin.copy:
        src: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
        dest: "{{ certs_dir }}cert.pem"
        owner: root
        group: root
        mode: '0644'

    - name: Copy private key to Nginx SSL directory
      ansible.builtin.copy:
        src: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
        dest: "{{ certs_dir }}key.pem"
        owner: root
        group: root
        mode: '0600'