---
- hosts: pce
  become: true
  vars:
      secrets_file: "../../secrets.tfvars"
      domain_name: "{{ (lookup('file', secrets_file) | regex_search('domain_name\\s*=\\s*\"(.*?)\"', '\\1')) | first }}"
      fqdn: "{{ inventory_hostname }}.{{ domain_name }}"

  tasks:
    - name: Install Certbot and Route 53 plugin using yum
      ansible.builtin.yum:
        name:
          - certbot
          - python3-certbot-dns-route53
        state: present
      tags: install

    - name: Display the fqdn
      debug:
        msg: "The requesting cert for: {{ fqdn }}"
      tags: obtain_cert

    - name: Obtain Let's Encrypt certificate using DNS challenge (Route 53)
      ansible.builtin.command:
        cmd: >
          certbot certonly --dns-route53
          -d {{ fqdn }}
          --non-interactive
          --agree-tos
          --email "anonymous@anonymous.com"
          --key-type rsa
      tags: obtain_cert

    - name: Copy Let's Encrypt root certificate to system trust store
      copy:
        src: "/etc/letsencrypt/live/{{ fqdn }}/chain.pem"
        dest: /etc/pki/ca-trust/source/anchors/letsencrypt-root.crt
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      tags: update_trust

    - name: Update the CA trust store to include the new certificate
      command: update-ca-trust
      tags: update_trust